FROM python:3.10-alpine
COPY . /app
WORKDIR /app
RUN python -mvenv .venv \
	&& source .venv/bin/activate \
	&& pip install -r requirements.txt \
	&& pip install gunicorn
CMD [ "gunicorn", "-c", "${GUNICORN_CONFIG}" ]
